<?php

namespace Modules\Job\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (DB::table('jobs')->count() === 0) {

            DB::table('jobs')->insert([
                [
                    'company_id' => 1,
                    'job_title' => 'Maintrol Engineer',
                    'job_location' => 'London Area, United Kingdom',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => '<div class="jobs-box__html-content bWGMXaNhXbVYoGhCbtjjaDWnFrmbauSrGk t-14 t-normal jobs-description-content__text--stretch" id="job-details" tabindex="-1"><h2 class="text-heading-large">About the job</h2><div class="mt4"><p dir="ltr"><span><strong>This is an initial 1 month contract providing on-site Desktop Support, with the possibility it may extend on beyond 1 month.<span><br></span><span><br></span></strong></span><span><strong>The role:<span><br></span><span><br></span></strong></span><span></span></p><ul><span><li>Handle Incidents and Service Requests and near desk support;</li></span><span><li>Provide services to End Users that include the following:</li></span><span><li>End User Devices including workstations, desktop PCs, laptop/notebook PCs, tablet PCs,</li></span><span><li>Collaboration and Communication services and devices including smart phones, desktop phones, mobility devices, streaming media systems (video conferencing) and other End User computing Hardware devices and associated system Software;</li></span><span><li>Network-attached devices (e.g. printers, scanners, copiers, multi-functional devices (e.g. printer/scanner/fax);</li></span><span><li>Locally-attached devices (e.g. personal printers, projectors);</li></span><span><li>Daily health checks to End User Devices and Network attached devices as required</li></span><span><li>Meeting room support as required.</li></span><span><li>Provide effective Deskside Support Services in accordance with the appropriate Performance Standards;<span><br></span><span><br></span></li></span></ul><span><strong>About you:<span><br></span><span><br></span></strong></span><span><ul><span><li>You will have a minimum 2-3 years’ experience in Windows Desktop support.</li></span><span><li>Experience in:</li></span><span><li>Windows 7-10, Microsoft Active Directory, utilization of GPOs, MS Office 365, PC hardware installation and troubleshooting, Enterprise anti-virus solutions, Helpdesk ticketing systems (e.g. ServiceNow).</li></span><span><li>Mobile device management including IOS and Android devices, Enterprise encryption solutions, Windows PC/laptop management via Active Directory.</li></span><span><li>Proven analytical, troubleshooting, and problem-solving skills.</li></span><span><li>The ability to multi-task, effectively determine priorities and meet SLA’s.</li></span><span><li>Excellent communication, rapport building and internal customer service skills.<span><br></span><span><br></span></li></span></ul></span>A&amp;O IT Group<span><br></span><span><br></span>As a successful and growing global IT services provider, A&amp;O IT Group deliver ‘fully managed’ IT solutions and cyber security services. Combining over 50 years expertise, and boasting an extensive global network, whilst remaining privately owned, A&amp;O IT Group is a trusted IT services partner to clients globally.<span><br></span><span><br></span><span><em>This role is subject to a post-offer Background Verification in accordance with the local country legislation.<span><br></span><span><br></span></em></span>Learn more about life at A&amp;O IT Group and our opportunities on our website<span class="white-space-pre"></span><span><strong><span><em>IT Engineer Careers<span class="white-space-pre"></span></em></span></strong></span>page.<span><br></span><span><br></span><span><strong>NO AGENCIES<span><br></span><span><br></span></strong></span><span><em>We encourage diversity and seek to attract individuals with unique backgrounds and perspectives. It is important that we build a team with a diverse mix of people and skills, where everyone feels welcome and able to succeed. We are committed to equal employment opportunity regardless of race, colour, religion, sex, sexual orientation, age, marital status, disability or gender identity.</em></span><p></p></div></div>',
                    'requirements' => 'Experience in aircraft maintenance and relevant engineering degree.',
                    'responsibilities' => 'Coordinate maintenance schedules, ensure compliance with aviation standards.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 1,
                    'job_title' => 'CAMO Engineer',
                    'job_location' => 'Valletta, Malta',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => '<div class="jobs-box__html-content bWGMXaNhXbVYoGhCbtjjaDWnFrmbauSrGk t-14 t-normal jobs-description-content__text--stretch" id="job-details" tabindex="-1"><h2 class="text-heading-large">About the job</h2><div class="mt4"><p dir="ltr"><span><strong>This is an initial 1 month contract providing on-site Desktop Support, with the possibility it may extend on beyond 1 month.<span><br></span><span><br></span></strong></span><span><strong>The role:<span><br></span><span><br></span></strong></span><span></span></p><ul><span><li>Handle Incidents and Service Requests and near desk support;</li></span><span><li>Provide services to End Users that include the following:</li></span><span><li>End User Devices including workstations, desktop PCs, laptop/notebook PCs, tablet PCs,</li></span><span><li>Collaboration and Communication services and devices including smart phones, desktop phones, mobility devices, streaming media systems (video conferencing) and other End User computing Hardware devices and associated system Software;</li></span><span><li>Network-attached devices (e.g. printers, scanners, copiers, multi-functional devices (e.g. printer/scanner/fax);</li></span><span><li>Locally-attached devices (e.g. personal printers, projectors);</li></span><span><li>Daily health checks to End User Devices and Network attached devices as required</li></span><span><li>Meeting room support as required.</li></span><span><li>Provide effective Deskside Support Services in accordance with the appropriate Performance Standards;<span><br></span><span><br></span></li></span></ul><span><strong>About you:<span><br></span><span><br></span></strong></span><span><ul><span><li>You will have a minimum 2-3 years’ experience in Windows Desktop support.</li></span><span><li>Experience in:</li></span><span><li>Windows 7-10, Microsoft Active Directory, utilization of GPOs, MS Office 365, PC hardware installation and troubleshooting, Enterprise anti-virus solutions, Helpdesk ticketing systems (e.g. ServiceNow).</li></span><span><li>Mobile device management including IOS and Android devices, Enterprise encryption solutions, Windows PC/laptop management via Active Directory.</li></span><span><li>Proven analytical, troubleshooting, and problem-solving skills.</li></span><span><li>The ability to multi-task, effectively determine priorities and meet SLA’s.</li></span><span><li>Excellent communication, rapport building and internal customer service skills.<span><br></span><span><br></span></li></span></ul></span>A&amp;O IT Group<span><br></span><span><br></span>As a successful and growing global IT services provider, A&amp;O IT Group deliver ‘fully managed’ IT solutions and cyber security services. Combining over 50 years expertise, and boasting an extensive global network, whilst remaining privately owned, A&amp;O IT Group is a trusted IT services partner to clients globally.<span><br></span><span><br></span><span><em>This role is subject to a post-offer Background Verification in accordance with the local country legislation.<span><br></span><span><br></span></em></span>Learn more about life at A&amp;O IT Group and our opportunities on our website<span class="white-space-pre"></span><span><strong><span><em>IT Engineer Careers<span class="white-space-pre"></span></em></span></strong></span>page.<span><br></span><span><br></span><span><strong>NO AGENCIES<span><br></span><span><br></span></strong></span><span><em>We encourage diversity and seek to attract individuals with unique backgrounds and perspectives. It is important that we build a team with a diverse mix of people and skills, where everyone feels welcome and able to succeed. We are committed to equal employment opportunity regardless of race, colour, religion, sex, sexual orientation, age, marital status, disability or gender identity.</em></span><p></p></div></div>',
                    'requirements' => 'Experience in CAMO operations and relevant certification.',
                    'responsibilities' => 'Oversee maintenance planning and ensure regulatory compliance.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 1,
                    'job_title' => 'Avionics Technicians',
                    'job_location' => 'Birmingham, England, United Kingdom',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => '<article class="jobs-description__container"><div class="jobs-description__content jobs-description-content"><div class="jobs-box__html-content bWGMXaNhXbVYoGhCbtjjaDWnFrmbauSrGk t-14 t-normal jobs-description-content__text--stretch" id="job-details" tabindex="-1"><h2 class="text-heading-large">About the job</h2><div class="mt4"><p dir="ltr"><span><p>Position :<span class="white-space-pre"></span><span><strong>SHOPIFY DEVELOPER</strong></span></p></span><span><p>Quantity : 03 (1 senior – 2 middle)</p></span><span><p>Type : Full-time</p></span><span><p>Location : 2nd Floor, DREAM STATION COWORKING, Udic Complex Building, Hoang Dao Thuy St., Trung Hoa Ward, Cau Giay Dist,. Hanoi Capital, Vietnam</p></span><span><p><span><strong>Working Location : Hanoi Capital</strong></span></p></span><span><p><span><strong>ABOUT US</strong></span></p></span><span><p>Astek is a global player in engineering and technology consulting, founded in France in 1988. Today, we are +7500 engineers across over 22 countries in the world.</p></span><span><p>With expertise in many industrial and tertiary sectors, we support our international clients in the intelligent deployment of their products and services, and in the implementation of their digital transformation.</p></span><span><p>Astek Vietnam is established in 2022 to increase group’s capability to support our clients’ operation around the globe, leveraging Vietnam talented engineers.<span class="white-space-pre"></span></p></span><span><p>More information about our group: https://astekgroup.fr/</p></span><span><p><span><strong>JOB DESCRIPTION &amp; REQUIREMENTS</strong></span></p></span><span><p><span class="white-space-pre"></span>Scope of Work: Responsibility for providing a fully functional Digital Factory team, responsible for:<span class="white-space-pre"></span></p></span><span><p>• Creation of new websites o Shopify websites<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Building and publishing custom apps (Shopify CLI)<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Integration with external systems - CRM, WMS, ERP etc<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Headless commerce understanding<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Other websites<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Drupal CMS</p></span><span><p><span class="white-space-pre"></span>• Maintenance of existing websites<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Reverse engineering and optimization of existing code<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Website migration to The CLIENT environment<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Website maintenance (evolution, content management, etc.)<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Code versioning management<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Security remediations<span class="white-space-pre"></span></p></span><span><p>• For all websites, must be followed<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Website development with security by design mindset<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Website deployment through CI/CD, using standard deployment steps (development, UAT, production)<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Management of cookie banners via OneTrust<span class="white-space-pre"></span></p></span><span><p><span class="white-space-pre"></span>§ Partnering with The CLIENT domain management and Akamai teams</p></span><span><p><span class="white-space-pre"></span>Find the solutions for old platform to Shopify/DRUPALè Understand existing website and determine solution for migrating to Shopify/Drupal</p></span><span><p><span><br></span></p></span><span><p><span><strong>REQUIREMENT</strong></span></p></span><span><p>● Maintain websites for customers</p></span><span><p>● Optimize for the Shopify site</p></span><span><p>● Find the solutions for old platform to Shopify</p></span><span><p>● Self-build theme(Base on Debut) Ajax cart, Quick add, Ajax filter, and CMS Sections.</p></span><span><p>● Custom checkout page(Shopify Plus)</p></span><span><p>● Build the subscription product</p></span><span><p>● Build the Color swatch</p></span><span><p>● Build the Filters</p></span><span><p>● Custom variant display on product</p></span><span><p>● Strong in fixing errors</p></span><span><p>● Experience with Shopify Webhook</p></span><span><p>● Experience with Shopify Event</p></span><span><p>● And more with Shopify Theme</p></span><span><p>● Willingness to learn, explore and self-teach.</p></span><span><p>● Ability to work collaboratively in a team</p></span><span><p>● Good speaking and writing skills in English to interact effectively with all the teams in each country</p></span><span><p><span><strong>BENEFITS</strong></span></p></span><span><ul><span><li>Attractive salary: Nego. Performance based award.</li></span><span><li>Young and dynamic working environment.</li></span><span><li>Continuous development of hard and soft skills through work and professional trainings.</li></span><span><li>Opportunity to approach newest technology trends.</li></span><span><li>Salary reviews 1 times/year or on excellent performance</li></span><span><li>Company’s labor policy completely pursuant to Vietnamese labor legislation plus other benefits offered by the company (Company trip, Holiday, etc.)</li></span></ul></span><span><p><span><strong>CONTACT</strong></span></p></span><span><p><span><strong>ASTEK VIETNAM</strong></span></p></span><span><ul><span><li><span><strong>Contact Person: Mrs. Dzung</strong></span></li></span><span><li><span><strong>Phone Number: 0969988029</strong></span></li></span><span><li><span><strong>Email: dzungnguyen@groupeastek.vn</strong></span></li></span><span><li><span><strong>Website:<span class="white-space-pre"></span></strong></span><a class="pTSsSJsLzRLkMbyTaIxqYJTfuyzbqtZqJVgQ" target="_blank" href="https://astekgroup.fr/?lang=en" data-test-app-aware-link="">https://astekgroup.fr/?lang=en</a></li></span></ul></span></p></div></div><div class="jobs-description__details"></div></div></article>',
                    'requirements' => 'Experience in avionics troubleshooting and repair.',
                    'responsibilities' => 'Repair and maintain avionics systems on commercial aircraft.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 1,
                    'job_title' => 'Maintenance Operations Controller',
                    'job_location' => 'Valletta, Malta',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(1)->toDateString(),
                    'description' => 'Control maintenance operations and coordinate maintenance schedules.',
                    'requirements' => 'Previous experience in maintenance operations.',
                    'responsibilities' => 'Monitor and coordinate maintenance activities for aircraft.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 1,
                    'job_title' => 'B1/B2 Licensed Engineer',
                    'job_location' => 'Birmingham, England, United Kingdom',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Perform inspections and certify maintenance work on aircraft.',
                    'requirements' => 'Valid B1/B2 license with relevant experience.',
                    'responsibilities' => 'Inspect and certify maintenance activities as per aviation regulations.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 1,
                    'job_title' => 'Aircraft Mechanics',
                    'job_location' => 'Birmingham, England, United Kingdom',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subDays(4)->toDateString(),
                    'description' => 'Perform maintenance and repairs on aircraft mechanical systems.',
                    'requirements' => 'Experience in aircraft mechanics and relevant certifications.',
                    'responsibilities' => 'Maintain and repair aircraft systems ensuring compliance with safety standards.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 1,
                    'job_title' => 'Base Maintenance Manager',
                    'job_location' => 'Larnaca, Cyprus',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Lead and manage base maintenance operations.',
                    'requirements' => 'Experience in managing maintenance teams and operations.',
                    'responsibilities' => 'Oversee maintenance activities and ensure quality control.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 1,
                    'job_title' => 'B1/B2 Licensed Engineer',
                    'job_location' => 'Larnaca, Cyprus',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Perform inspections and certify maintenance work on aircraft.',
                    'requirements' => 'Valid B1/B2 license with relevant experience.',
                    'responsibilities' => 'Inspect and certify maintenance activities as per aviation regulations.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 1,
                    'job_title' => 'Base Maintenance Check Manager',
                    'job_location' => 'Manchester Area, United Kingdom',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Oversee base maintenance checks and ensure compliance.',
                    'requirements' => 'Experience in maintenance management and aviation regulations.',
                    'responsibilities' => 'Lead maintenance check processes ensuring adherence to standards.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 2,
                    'job_title' => 'Practicante de Arquitectura o Ingenieria Civil',
                    'job_location' => 'Trujillo, La Libertad, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(4)->toDateString(),
                    'description' => 'Support the architectural or civil engineering projects at different stages.',
                    'requirements' => 'Student or recent graduate in Architecture or Civil Engineering.',
                    'responsibilities' => 'Assist in design, drafting, and project management activities.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 2,
                    'job_title' => 'Practicante de Sistemas',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(1)->toDateString(),
                    'description' => 'Assist in IT operations and support systems maintenance.',
                    'requirements' => 'Student or recent graduate in Computer Systems or related field.',
                    'responsibilities' => 'Support software, hardware, and network activities.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 2,
                    'job_title' => 'Practicante Profesional de Logistica',
                    'job_location' => 'Trujillo, La Libertad, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => 'Assist in managing logistics and supply chain operations.',
                    'requirements' => 'Knowledge of logistics processes and tools.',
                    'responsibilities' => 'Help in inventory management, vendor coordination, and delivery tracking.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 2,
                    'job_title' => 'Supervisor de Ventas Provincias - Oriente',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(2)->toDateString(),
                    'description' => 'Supervise sales activities and manage regional sales representatives.',
                    'requirements' => 'Experience in sales supervision, good communication skills.',
                    'responsibilities' => 'Ensure targets are met, manage sales staff, and report on performance.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 2,
                    'job_title' => 'Practicante de Aseguramiento de la Calidad - Materiales y Envasado',
                    'job_location' => 'Trujillo, La Libertad, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(1)->toDateString(),
                    'description' => 'Assist in quality assurance processes for materials and packaging.',
                    'requirements' => 'Knowledge of quality control and quality assurance standards.',
                    'responsibilities' => 'Inspect materials, ensure packaging quality, and document results.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 2,
                    'job_title' => 'Practicante de Marketing',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => 'Support marketing campaigns and social media management.',
                    'requirements' => 'Student or recent graduate in Marketing or Communications.',
                    'responsibilities' => 'Assist in developing marketing materials and managing campaigns.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 2,
                    'job_title' => 'Asistente de Gestión del Talento',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(1)->toDateString(),
                    'description' => 'Assist in the talent management and recruitment process.',
                    'requirements' => 'Interest in human resources and talent acquisition.',
                    'responsibilities' => 'Schedule interviews, assist with onboarding, and maintain HR records.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 2,
                    'job_title' => 'Asistente de Trade Marketing',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(2)->toDateString(),
                    'description' => 'Assist in executing trade marketing strategies.',
                    'requirements' => 'Knowledge of marketing and sales promotion.',
                    'responsibilities' => 'Coordinate in-store marketing activities and promotional events.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 2,
                    'job_title' => 'Practicante de Trade Marketing',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => 'Assist in implementing trade marketing strategies.',
                    'requirements' => 'Student or recent graduate in Marketing or Business.',
                    'responsibilities' => 'Support trade marketing activities and help with event coordination.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 2,
                    'job_title' => 'Ayudante de Almacén',
                    'job_location' => 'Ate, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => 'Assist in warehouse activities including inventory management and order picking.',
                    'requirements' => 'Basic knowledge of warehouse operations.',
                    'responsibilities' => 'Help organize inventory, pick orders, and maintain cleanliness.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 3,
                    'job_title' => 'Junior GRC Consultant (Governance, Risk and Compliance)',
                    'job_location' => 'São Paulo, São Paulo, Brazil',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Responsibilities related to Governance, Risk, and Compliance (GRC).',
                    'requirements' => 'Skills in governance, risk management, and compliance.',
                    'responsibilities' => 'Collaborate with teams on risk management and compliance strategies.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 3,
                    'job_title' => 'Junior GRC Consultant',
                    'job_location' => 'Portugal (Remote)',
                    'job_type' => 'remote',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Support GRC projects and clients remotely.',
                    'requirements' => 'Strong communication and analytical skills.',
                    'responsibilities' => 'Help clients improve compliance and risk management practices.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 3,
                    'job_title' => 'SIEM Specialist',
                    'job_location' => 'Brazil (Remote)',
                    'job_type' => 'remote',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Monitor and manage SIEM systems and ensure security event responses.',
                    'requirements' => 'Experience with security platforms and tools.',
                    'responsibilities' => 'Handle security incidents and optimize SIEM performance.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 3,
                    'job_title' => 'Customer Success Manager',
                    'job_location' => 'São Paulo, Brazil (Remote)',
                    'job_type' => 'remote',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Ensure customer satisfaction and foster strong client relationships.',
                    'requirements' => 'Excellent organizational and interpersonal skills.',
                    'responsibilities' => 'Work closely with customers to deliver successful outcomes.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 3,
                    'job_title' => 'CSIRT Specialist',
                    'job_location' => 'Brazil (Remote)',
                    'job_type' => 'remote',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Collaborate with the incident response team to address cyber threats.',
                    'requirements' => 'Proficiency in cybersecurity and incident response techniques.',
                    'responsibilities' => 'Identify, assess, and respond to cybersecurity incidents.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 3,
                    'job_title' => 'ISO 27001 Consultant (Junior)',
                    'job_location' => 'Madrid, Spain (On-site)',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Assist organizations in implementing ISO 27001 standards.',
                    'requirements' => 'Knowledge of ISO standards and compliance processes.',
                    'responsibilities' => 'Support clients in achieving ISO 27001 certification.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 3,
                    'job_title' => 'Regional Sales Director - Southeast Region',
                    'job_location' => 'United States (Remote)',
                    'job_type' => 'remote',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Lead sales operations and strategies for the Southeast region.',
                    'requirements' => 'Proven experience in sales leadership roles.',
                    'responsibilities' => 'Develop and execute regional sales strategies.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 4,
                    'job_title' => 'Functioneel ICT Ketenbeheerder',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Responsible for ICT chain management and optimization.',
                    'requirements' => 'Experience in ICT chain management.',
                    'responsibilities' => 'Ensure smooth operation of ICT processes.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 4,
                    'job_title' => 'Stage Data Science',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Support data science projects as an intern.',
                    'requirements' => 'Knowledge of data analysis and machine learning.',
                    'responsibilities' => 'Assist with data modeling and analysis.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 4,
                    'job_title' => 'Commercieel Support Medewerker',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Provide commercial support for business operations.',
                    'requirements' => 'Strong communication and organizational skills.',
                    'responsibilities' => 'Support sales and marketing teams.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 4,
                    'job_title' => 'Werkstudent Strategie & Research',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'part-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Assist in strategic planning and research projects.',
                    'requirements' => 'Strong analytical and research skills.',
                    'responsibilities' => 'Work on research and strategic initiatives.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 4,
                    'job_title' => 'Analist Reporting',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Prepare and analyze financial reports.',
                    'requirements' => 'Experience in financial analysis and reporting.',
                    'responsibilities' => 'Generate regular financial reports.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 4,
                    'job_title' => 'IT Inkoper en Uitbestedingsmanager',
                    'job_location' => 'Groningen, Groningen, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Manage IT procurement and outsourcing.',
                    'requirements' => 'Experience in IT procurement and contract management.',
                    'responsibilities' => 'Oversee IT outsourcing contracts.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 4,
                    'job_title' => 'Werkstudent Vermogensbeheer',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'part-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Support asset management projects.',
                    'requirements' => 'Interest in financial markets and asset management.',
                    'responsibilities' => 'Assist with asset management tasks.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 4,
                    'job_title' => 'Klantenservicemedewerker',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Provide excellent customer service support.',
                    'requirements' => 'Strong customer service skills.',
                    'responsibilities' => 'Handle customer inquiries and complaints.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 4,
                    'job_title' => 'Meewerkstage Campus Recruitment',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Assist with campus recruitment activities.',
                    'requirements' => 'Interest in recruitment and talent acquisition.',
                    'responsibilities' => 'Support recruitment initiatives.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 4,
                    'job_title' => 'Microsoft 365 Specialist',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Specialize in Microsoft 365 administration and support.',
                    'requirements' => 'Experience with Microsoft 365 tools and administration.',
                    'responsibilities' => 'Manage and support Microsoft 365 environments.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 5,
                    'job_title' => 'Practicante Pre Profesional Legal',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subDays(2)->toDateString(),
                    'description' => 'Support in legal professional practices.',
                    'requirements' => 'Law student with strong analytical skills.',
                    'responsibilities' => 'Assist in legal case management and research.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 5,
                    'job_title' => 'Practicante Profesional de Ingeniería Alimentaria',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(1)->toDateString(),
                    'description' => 'Assist in food engineering processes.',
                    'requirements' => 'Student or graduate in Food Engineering.',
                    'responsibilities' => 'Support product quality assurance and development.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 5,
                    'job_title' => 'Analista de Seguridad de la Información',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(4)->toDateString(),
                    'description' => 'Analyze and ensure information security.',
                    'requirements' => 'Experience in IT security and risk management.',
                    'responsibilities' => 'Monitor and mitigate IT security threats.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 5,
                    'job_title' => 'Analista de Investigación & Desarrollo',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(4)->toDateString(),
                    'description' => 'Research and develop new products.',
                    'requirements' => 'Experience in R&D or product innovation.',
                    'responsibilities' => 'Work on product formulation and testing.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 5,
                    'job_title' => 'Analista de Programaciones Web y Aplicaciones',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(1)->toDateString(),
                    'description' => 'Develop and maintain web applications.',
                    'requirements' => 'Proficiency in web programming languages.',
                    'responsibilities' => 'Collaborate with teams to build scalable applications.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 5,
                    'job_title' => 'Analista de Investigación & Desarrollo',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subDays(2)->toDateString(),
                    'description' => 'Research and develop innovative solutions.',
                    'requirements' => 'Strong background in research methodologies.',
                    'responsibilities' => 'Lead R&D projects for product improvement.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 7,
                    'job_title' => 'IT Business Analyst - Aksaray',
                    'job_location' => 'Aksaray, Aksaray, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->toDateString(),
                    'description' => 'Analyze business requirements and implement IT solutions.',
                    'requirements' => 'Strong background in IT and business analysis.',
                    'responsibilities' => 'Collaborate with stakeholders and manage IT projects.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 7,
                    'job_title' => 'Facility Mechanical Maintenance Engineer',
                    'job_location' => 'Greater Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Maintain and improve mechanical facilities.',
                    'requirements' => 'Experience in mechanical maintenance and engineering.',
                    'responsibilities' => 'Inspect, repair, and optimize facility equipment.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 7,
                    'job_title' => 'Senior Financial Analyst - MB Segment Steering & Reporting Model',
                    'job_location' => 'Istanbul, Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Provide financial analysis and reporting for MB segments.',
                    'requirements' => 'Experience in financial analysis and reporting.',
                    'responsibilities' => 'Prepare financial models and forecasts.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 7,
                    'job_title' => 'Accounts Payable Specialist',
                    'job_location' => 'Istanbul, Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeek()->toDateString(),
                    'description' => 'Manage accounts payable processes.',
                    'requirements' => 'Knowledge of accounting principles and ERP systems.',
                    'responsibilities' => 'Process invoices and manage vendor payments.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 7,
                    'job_title' => 'Lojistik Süreç Sorumlusu',
                    'job_location' => 'Istanbul, Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subDays(3)->toDateString(),
                    'description' => 'Oversee and manage logistics processes.',
                    'requirements' => 'Experience in logistics and supply chain management.',
                    'responsibilities' => 'Coordinate supply chain operations.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 7,
                    'job_title' => 'Material Supply Specialist (Aksaray)',
                    'job_location' => 'Aksaray, Aksaray, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Ensure efficient supply of materials.',
                    'requirements' => 'Experience in material supply and logistics.',
                    'responsibilities' => 'Plan and manage material supply operations.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 7,
                    'job_title' => 'Production & Facilities, Automation & Maintenance Engineer',
                    'job_location' => 'Greater Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Work on automation and maintenance for production facilities.',
                    'requirements' => 'Experience in production automation and maintenance.',
                    'responsibilities' => 'Develop and maintain automated production processes.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 7,
                    'job_title' => 'CAE Engineer',
                    'job_location' => 'Greater Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Conduct computer-aided engineering analyses.',
                    'requirements' => 'Proficiency in CAE tools and engineering principles.',
                    'responsibilities' => 'Perform simulations and validate designs.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 7,
                    'job_title' => 'Otobüs SSH Teknik Yöneticisi',
                    'job_location' => 'Istanbul, Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => 'Manage technical operations for bus services.',
                    'requirements' => 'Technical expertise in bus systems and operations.',
                    'responsibilities' => 'Oversee bus maintenance and service quality.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 8,
                    'job_title' => 'Maintrol Engineer',
                    'job_location' => 'London Area, United Kingdom',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => 'Responsible for aircraft maintenance control and overall engineering tasks.',
                    'requirements' => 'Experience in aircraft maintenance and relevant engineering degree.',
                    'responsibilities' => 'Coordinate maintenance schedules, ensure compliance with aviation standards.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 8,
                    'job_title' => 'CAMO Engineer',
                    'job_location' => 'Valletta, Malta',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'CAMO engineering role focused on compliance and maintenance planning.',
                    'requirements' => 'Experience in CAMO operations and relevant certification.',
                    'responsibilities' => 'Oversee maintenance planning and ensure regulatory compliance.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 8,
                    'job_title' => 'Avionics Technicians',
                    'job_location' => 'Birmingham, England, United Kingdom',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Perform diagnostics and repairs on avionics systems.',
                    'requirements' => 'Experience in avionics troubleshooting and repair.',
                    'responsibilities' => 'Repair and maintain avionics systems on commercial aircraft.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 8,
                    'job_title' => 'Maintenance Operations Controller',
                    'job_location' => 'Valletta, Malta',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(1)->toDateString(),
                    'description' => 'Control maintenance operations and coordinate maintenance schedules.',
                    'requirements' => 'Previous experience in maintenance operations.',
                    'responsibilities' => 'Monitor and coordinate maintenance activities for aircraft.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 8,
                    'job_title' => 'B1/B2 Licensed Engineer',
                    'job_location' => 'Birmingham, England, United Kingdom',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Perform inspections and certify maintenance work on aircraft.',
                    'requirements' => 'Valid B1/B2 license with relevant experience.',
                    'responsibilities' => 'Inspect and certify maintenance activities as per aviation regulations.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 8,
                    'job_title' => 'Aircraft Mechanics',
                    'job_location' => 'Birmingham, England, United Kingdom',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subDays(4)->toDateString(),
                    'description' => 'Perform maintenance and repairs on aircraft mechanical systems.',
                    'requirements' => 'Experience in aircraft mechanics and relevant certifications.',
                    'responsibilities' => 'Maintain and repair aircraft systems ensuring compliance with safety standards.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 8,
                    'job_title' => 'Base Maintenance Manager',
                    'job_location' => 'Larnaca, Cyprus',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Lead and manage base maintenance operations.',
                    'requirements' => 'Experience in managing maintenance teams and operations.',
                    'responsibilities' => 'Oversee maintenance activities and ensure quality control.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 8,
                    'job_title' => 'B1/B2 Licensed Engineer',
                    'job_location' => 'Larnaca, Cyprus',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Perform inspections and certify maintenance work on aircraft.',
                    'requirements' => 'Valid B1/B2 license with relevant experience.',
                    'responsibilities' => 'Inspect and certify maintenance activities as per aviation regulations.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 8,
                    'job_title' => 'Base Maintenance Check Manager',
                    'job_location' => 'Manchester Area, United Kingdom',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Oversee base maintenance checks and ensure compliance.',
                    'requirements' => 'Experience in maintenance management and aviation regulations.',
                    'responsibilities' => 'Lead maintenance check processes ensuring adherence to standards.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 9,
                    'job_title' => 'Practicante de Arquitectura o Ingenieria Civil',
                    'job_location' => 'Trujillo, La Libertad, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(4)->toDateString(),
                    'description' => 'Support the architectural or civil engineering projects at different stages.',
                    'requirements' => 'Student or recent graduate in Architecture or Civil Engineering.',
                    'responsibilities' => 'Assist in design, drafting, and project management activities.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 9,
                    'job_title' => 'Practicante de Sistemas',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(1)->toDateString(),
                    'description' => 'Assist in IT operations and support systems maintenance.',
                    'requirements' => 'Student or recent graduate in Computer Systems or related field.',
                    'responsibilities' => 'Support software, hardware, and network activities.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 9,
                    'job_title' => 'Practicante Profesional de Logistica',
                    'job_location' => 'Trujillo, La Libertad, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => 'Assist in managing logistics and supply chain operations.',
                    'requirements' => 'Knowledge of logistics processes and tools.',
                    'responsibilities' => 'Help in inventory management, vendor coordination, and delivery tracking.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 9,
                    'job_title' => 'Supervisor de Ventas Provincias - Oriente',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(2)->toDateString(),
                    'description' => 'Supervise sales activities and manage regional sales representatives.',
                    'requirements' => 'Experience in sales supervision, good communication skills.',
                    'responsibilities' => 'Ensure targets are met, manage sales staff, and report on performance.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 9,
                    'job_title' => 'Practicante de Aseguramiento de la Calidad - Materiales y Envasado',
                    'job_location' => 'Trujillo, La Libertad, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(1)->toDateString(),
                    'description' => 'Assist in quality assurance processes for materials and packaging.',
                    'requirements' => 'Knowledge of quality control and quality assurance standards.',
                    'responsibilities' => 'Inspect materials, ensure packaging quality, and document results.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 9,
                    'job_title' => 'Practicante de Marketing',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => 'Support marketing campaigns and social media management.',
                    'requirements' => 'Student or recent graduate in Marketing or Communications.',
                    'responsibilities' => 'Assist in developing marketing materials and managing campaigns.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 9,
                    'job_title' => 'Asistente de Gestión del Talento',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(1)->toDateString(),
                    'description' => 'Assist in the talent management and recruitment process.',
                    'requirements' => 'Interest in human resources and talent acquisition.',
                    'responsibilities' => 'Schedule interviews, assist with onboarding, and maintain HR records.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 9,
                    'job_title' => 'Asistente de Trade Marketing',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(2)->toDateString(),
                    'description' => 'Assist in executing trade marketing strategies.',
                    'requirements' => 'Knowledge of marketing and sales promotion.',
                    'responsibilities' => 'Coordinate in-store marketing activities and promotional events.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 9,
                    'job_title' => 'Practicante de Trade Marketing',
                    'job_location' => 'Lima, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => 'Assist in implementing trade marketing strategies.',
                    'requirements' => 'Student or recent graduate in Marketing or Business.',
                    'responsibilities' => 'Support trade marketing activities and help with event coordination.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 9,
                    'job_title' => 'Ayudante de Almacén',
                    'job_location' => 'Ate, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => 'Assist in warehouse activities including inventory management and order picking.',
                    'requirements' => 'Basic knowledge of warehouse operations.',
                    'responsibilities' => 'Help organize inventory, pick orders, and maintain cleanliness.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 10,
                    'job_title' => 'Junior GRC Consultant (Governance, Risk and Compliance)',
                    'job_location' => 'São Paulo, São Paulo, Brazil',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Responsibilities related to Governance, Risk, and Compliance (GRC).',
                    'requirements' => 'Skills in governance, risk management, and compliance.',
                    'responsibilities' => 'Collaborate with teams on risk management and compliance strategies.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 10,
                    'job_title' => 'Junior GRC Consultant',
                    'job_location' => 'Portugal (Remote)',
                    'job_type' => 'remote',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Support GRC projects and clients remotely.',
                    'requirements' => 'Strong communication and analytical skills.',
                    'responsibilities' => 'Help clients improve compliance and risk management practices.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 10,
                    'job_title' => 'SIEM Specialist',
                    'job_location' => 'Brazil (Remote)',
                    'job_type' => 'remote',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Monitor and manage SIEM systems and ensure security event responses.',
                    'requirements' => 'Experience with security platforms and tools.',
                    'responsibilities' => 'Handle security incidents and optimize SIEM performance.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 10,
                    'job_title' => 'Customer Success Manager',
                    'job_location' => 'São Paulo, Brazil (Remote)',
                    'job_type' => 'remote',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Ensure customer satisfaction and foster strong client relationships.',
                    'requirements' => 'Excellent organizational and interpersonal skills.',
                    'responsibilities' => 'Work closely with customers to deliver successful outcomes.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 10,
                    'job_title' => 'CSIRT Specialist',
                    'job_location' => 'Brazil (Remote)',
                    'job_type' => 'remote',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Collaborate with the incident response team to address cyber threats.',
                    'requirements' => 'Proficiency in cybersecurity and incident response techniques.',
                    'responsibilities' => 'Identify, assess, and respond to cybersecurity incidents.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 10,
                    'job_title' => 'ISO 27001 Consultant (Junior)',
                    'job_location' => 'Madrid, Spain (On-site)',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Assist organizations in implementing ISO 27001 standards.',
                    'requirements' => 'Knowledge of ISO standards and compliance processes.',
                    'responsibilities' => 'Support clients in achieving ISO 27001 certification.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 10,
                    'job_title' => 'Regional Sales Director - Southeast Region',
                    'job_location' => 'United States (Remote)',
                    'job_type' => 'remote',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Lead sales operations and strategies for the Southeast region.',
                    'requirements' => 'Proven experience in sales leadership roles.',
                    'responsibilities' => 'Develop and execute regional sales strategies.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 11,
                    'job_title' => 'Functioneel ICT Ketenbeheerder',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Responsible for ICT chain management and optimization.',
                    'requirements' => 'Experience in ICT chain management.',
                    'responsibilities' => 'Ensure smooth operation of ICT processes.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 11,
                    'job_title' => 'Stage Data Science',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Support data science projects as an intern.',
                    'requirements' => 'Knowledge of data analysis and machine learning.',
                    'responsibilities' => 'Assist with data modeling and analysis.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 11,
                    'job_title' => 'Commercieel Support Medewerker',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Provide commercial support for business operations.',
                    'requirements' => 'Strong communication and organizational skills.',
                    'responsibilities' => 'Support sales and marketing teams.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 11,
                    'job_title' => 'Werkstudent Strategie & Research',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'part-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Assist in strategic planning and research projects.',
                    'requirements' => 'Strong analytical and research skills.',
                    'responsibilities' => 'Work on research and strategic initiatives.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 11,
                    'job_title' => 'Analist Reporting',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Prepare and analyze financial reports.',
                    'requirements' => 'Experience in financial analysis and reporting.',
                    'responsibilities' => 'Generate regular financial reports.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 11,
                    'job_title' => 'IT Inkoper en Uitbestedingsmanager',
                    'job_location' => 'Groningen, Groningen, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Manage IT procurement and outsourcing.',
                    'requirements' => 'Experience in IT procurement and contract management.',
                    'responsibilities' => 'Oversee IT outsourcing contracts.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 11,
                    'job_title' => 'Werkstudent Vermogensbeheer',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'part-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Support asset management projects.',
                    'requirements' => 'Interest in financial markets and asset management.',
                    'responsibilities' => 'Assist with asset management tasks.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 11,
                    'job_title' => 'Klantenservicemedewerker',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Provide excellent customer service support.',
                    'requirements' => 'Strong customer service skills.',
                    'responsibilities' => 'Handle customer inquiries and complaints.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 11,
                    'job_title' => 'Meewerkstage Campus Recruitment',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Assist with campus recruitment activities.',
                    'requirements' => 'Interest in recruitment and talent acquisition.',
                    'responsibilities' => 'Support recruitment initiatives.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 11,
                    'job_title' => 'Microsoft 365 Specialist',
                    'job_location' => 'Utrecht, Utrecht, Netherlands',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Specialize in Microsoft 365 administration and support.',
                    'requirements' => 'Experience with Microsoft 365 tools and administration.',
                    'responsibilities' => 'Manage and support Microsoft 365 environments.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 12,
                    'job_title' => 'Practicante Pre Profesional Legal',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subDays(2)->toDateString(),
                    'description' => 'Support in legal professional practices.',
                    'requirements' => 'Law student with strong analytical skills.',
                    'responsibilities' => 'Assist in legal case management and research.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 12,
                    'job_title' => 'Practicante Profesional de Ingeniería Alimentaria',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(1)->toDateString(),
                    'description' => 'Assist in food engineering processes.',
                    'requirements' => 'Student or graduate in Food Engineering.',
                    'responsibilities' => 'Support product quality assurance and development.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 12,
                    'job_title' => 'Analista de Seguridad de la Información',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(4)->toDateString(),
                    'description' => 'Analyze and ensure information security.',
                    'requirements' => 'Experience in IT security and risk management.',
                    'responsibilities' => 'Monitor and mitigate IT security threats.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 12,
                    'job_title' => 'Analista de Investigación & Desarrollo',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(4)->toDateString(),
                    'description' => 'Research and develop new products.',
                    'requirements' => 'Experience in R&D or product innovation.',
                    'responsibilities' => 'Work on product formulation and testing.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 12,
                    'job_title' => 'Analista de Programaciones Web y Aplicaciones',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subMonths(1)->toDateString(),
                    'description' => 'Develop and maintain web applications.',
                    'requirements' => 'Proficiency in web programming languages.',
                    'responsibilities' => 'Collaborate with teams to build scalable applications.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 12,
                    'job_title' => 'Analista de Investigación & Desarrollo',
                    'job_location' => 'La Victoria, Peru',
                    'job_type' => 'onsite',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subDays(2)->toDateString(),
                    'description' => 'Research and develop innovative solutions.',
                    'requirements' => 'Strong background in research methodologies.',
                    'responsibilities' => 'Lead R&D projects for product improvement.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 13,
                    'job_title' => 'IT Business Analyst - Aksaray',
                    'job_location' => 'Aksaray, Aksaray, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->toDateString(),
                    'description' => 'Analyze business requirements and implement IT solutions.',
                    'requirements' => 'Strong background in IT and business analysis.',
                    'responsibilities' => 'Collaborate with stakeholders and manage IT projects.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 13,
                    'job_title' => 'Facility Mechanical Maintenance Engineer',
                    'job_location' => 'Greater Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Maintain and improve mechanical facilities.',
                    'requirements' => 'Experience in mechanical maintenance and engineering.',
                    'responsibilities' => 'Inspect, repair, and optimize facility equipment.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 13,
                    'job_title' => 'Senior Financial Analyst - MB Segment Steering & Reporting Model',
                    'job_location' => 'Istanbul, Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Provide financial analysis and reporting for MB segments.',
                    'requirements' => 'Experience in financial analysis and reporting.',
                    'responsibilities' => 'Prepare financial models and forecasts.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 13,
                    'job_title' => 'Accounts Payable Specialist',
                    'job_location' => 'Istanbul, Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeek()->toDateString(),
                    'description' => 'Manage accounts payable processes.',
                    'requirements' => 'Knowledge of accounting principles and ERP systems.',
                    'responsibilities' => 'Process invoices and manage vendor payments.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 13,
                    'job_title' => 'Lojistik Süreç Sorumlusu',
                    'job_location' => 'Istanbul, Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subDays(3)->toDateString(),
                    'description' => 'Oversee and manage logistics processes.',
                    'requirements' => 'Experience in logistics and supply chain management.',
                    'responsibilities' => 'Coordinate supply chain operations.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 13,
                    'job_title' => 'Material Supply Specialist (Aksaray)',
                    'job_location' => 'Aksaray, Aksaray, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Ensure efficient supply of materials.',
                    'requirements' => 'Experience in material supply and logistics.',
                    'responsibilities' => 'Plan and manage material supply operations.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 13,
                    'job_title' => 'Production & Facilities, Automation & Maintenance Engineer',
                    'job_location' => 'Greater Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Work on automation and maintenance for production facilities.',
                    'requirements' => 'Experience in production automation and maintenance.',
                    'responsibilities' => 'Develop and maintain automated production processes.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 13,
                    'job_title' => 'CAE Engineer',
                    'job_location' => 'Greater Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(3)->toDateString(),
                    'description' => 'Conduct computer-aided engineering analyses.',
                    'requirements' => 'Proficiency in CAE tools and engineering principles.',
                    'responsibilities' => 'Perform simulations and validate designs.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'company_id' => 13,
                    'job_title' => 'Otobüs SSH Teknik Yöneticisi',
                    'job_location' => 'Istanbul, Istanbul, Türkiye',
                    'job_type' => 'hybrid',
                    'employment_type' => 'full-time',
                    'open_date' => now()->subWeeks(2)->toDateString(),
                    'description' => 'Manage technical operations for bus services.',
                    'requirements' => 'Technical expertise in bus systems and operations.',
                    'responsibilities' => 'Oversee bus maintenance and service quality.',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
        }
    }
}
